apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: ytt/vendir/vsphere_cpi/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/tce.git
      ref: 9e70164c014c23bc47848a576cde10621bab4677
    includePaths:
    - addons/packages/vsphere-cpi/1.22.3/bundle/config/**/*
- path: ytt/vendir/cni/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/tce.git
      ref: 9dc64e01bfb67cc128f618a419415c0f73a82cdc
    includePaths:
    - addons/packages/antrea/0.13.3/bundle/config/**/*
    - addons/packages/calico/3.19.1/bundle/config/**/*
- path: ytt/vendir/kapp-controller/_ytt_lib
  contents:
  - path: .
    git:
      url: git@github.com:vmware-tanzu/community-edition.git
      ref: 0054c7f86937a0cfb9bd6dbc7501128fc06d4194
    includePaths:
    - addons/packages/kapp-controller/0.28.0/bundle/config/**/*
